model:
  name: residual_upsampler_slav
  path: models/
  extension: .pth
  in_channels: 3
  hidden_layers: 64
  res_blocks_number: 8
  upsample_factor: 4

train:
  device: cuda
  epochs: 20
  learning_rate: 0.0001
  batch_size: 16
  optimizer:
    name: Adam
    weight_decay: 0.00001
  image_crop_size: 256

dataset:
  name: DIV2K
  data_path: data/DIV2K

logging:
  log_dir: log/
  append: true